packages:
  - packages/**
catalog:
  '@antfu/eslint-config': 4.10.0
  '@nimiq/core': ^2.0.8
  '@nuxt/eslint': ^1.2.0
  '@nuxt/image': ^1.8.1
  '@nuxthub/core': ^0.8.3
  '@nuxtjs/color-mode': ^3.5.2
  '@pinia/nuxt': ^0.5.5
  '@types/node': ^22.9.0
  '@unocss/eslint-config': ^66.1.0-beta.6
  '@unocss/nuxt': ^0.63.6
  '@unocss/preset-rem-to-px': ^0.63.6
  '@unocss/reset': ^0.63.6
  '@unovis/ts': ^1.4.4
  '@unovis/vue': ^1.4.4
  '@vueuse/core': ^11.1.0
  '@vueuse/nuxt': ^11.1.0
  defu: ^6.1.4
  drizzle-kit: ^0.26.2
  drizzle-orm: ^0.35.3
  drizzle-zod: ^0.5.1
  eslint: ^9.13.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.7.0
  identicons-esm: ^0.2.1
  lint-staged: ^15.2.10
  nimiq-css: ^0.2.25
  nimiq-rpc-client-ts: ^1.0.0-beta.9
  nuxt: ^3.13.2
  pinia: ^2.2.4
  radix-vue: ^1.9.8
  simple-git-hooks: ^2.11.1
  svgo: ^3.3.2
  typescript: ^5.5.4
  unbuild: ^2.0.0
  unocss: ^66.1.0-beta.6
  vite: ^5.4.2
  vite-plugin-top-level-await: ^1.4.4
  vite-plugin-wasm: ^3.3.0
  vitest: ^2.0.5
  vue: ^3.5.12
  vue-router: ^4.4.5
  wrangler: ^3.83.0
  zod: ^3.23.8
