name: CI

on:
  push:
    branches:
      - '*'
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Set .env file
        run: echo "NUXT_PUBLIC_NIMIQ_NETWORK=test-albatross" > .env

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Validate JSON files
        run: pnpm run validate:json-files

      - name: Test
        run: pnpm run test
        env:
          NUXT_RPC_URL: ${{ secrets.RPC_URL_TESTNET }}
          NUXT_PUBLIC_NIMIQ_NETWORK: test-albatross
