name: Deploy to NuxtHub
on:
  push:
    branches:
      - '*'

jobs:
  deploy-testnet:
    name: Deploy to NuxtHub Testnet
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production-testnet' || 'preview-testnet' }}
      url: ${{ steps.deploy-testnet.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          NUXT_RPC_URL: ${{ secrets.NUXT_RPC_URL }}
          NUXT_PUBLIC_NIMIQ_NETWORK: ${{ vars.NUXT_PUBLIC_NIMIQ_NETWORK }}

      - name: Build application
        run: pnpm run build
        env:
          NUXT_RPC_URL: ${{ secrets.NUXT_RPC_URL }}
          NUXT_PUBLIC_NIMIQ_NETWORK: ${{ vars.NUXT_PUBLIC_NIMIQ_NETWORK }}

      - name: Deploy to NuxtHub ${{ vars.NUXT_HUB_ENV }} Testnet
        uses: nuxt-hub/action@v1
        id: deploy-testnet
        with:
          project-key: ${{ vars.NUXT_HUB_PROJECT_KEY }}

  deploy-mainnet:
    name: Deploy to NuxtHub Mainnet
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production-mainnet' || 'preview-mainnet' }}
      url: ${{ steps.deploy-mainnet.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          NUXT_RPC_URL: ${{ secrets.NUXT_RPC_URL }}
          NUXT_PUBLIC_NIMIQ_NETWORK: ${{ vars.NUXT_PUBLIC_NIMIQ_NETWORK }}

      - name: Build application
        run: pnpm run build
        env:
          NUXT_RPC_URL: ${{ secrets.NUXT_RPC_URL }}
          NUXT_PUBLIC_NIMIQ_NETWORK: ${{ vars.NUXT_PUBLIC_NIMIQ_NETWORK }}

      - name: Deploy to NuxtHub ${{ vars.NUXT_HUB_ENV }} Mainnet
        uses: nuxt-hub/action@v1
        id: deploy-mainnet
        with:
          project-key: ${{ vars.NUXT_HUB_PROJECT_KEY }}
