name: Sync Matrix

on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint:
          - https://validators-api-mainnet.pages.dev
          - https://validators-api-testnet.pages.dev
          - https://dev.validators-api-mainnet.pages.dev
          - https://dev.validators-api-testnet.pages.dev
    steps:
      # - name: Stream sync API
      #   run: |
      #     # --no-buffer (or -N) tells curl to flush each chunk as soon as it arrives,
      #     # so can see Nitro stream lines in real time.
      #     curl -fsS --no-buffer "${{ matrix.endpoint }}/api/v1/sync/sse" || {
      #       echo "Sync request failed for ${{ matrix.endpoint }}"
      #       exit 1
      #     }
      - name: Sync missing epochs
        env:
          ENDPOINT: ${{ matrix.endpoint }}
        run: |
          set -euo pipefail
          echo "🔄 Starting missing-epoch sync at $ENDPOINT"
          # Loop until the endpoint reports isSynced: true
          while true; do
            # Use -v for verbose output but redirect to a file
            error_file=$(mktemp)
            resp=$(curl -v -fsS "$ENDPOINT/api/v1/sync/missing-epoch" 2>"$error_file" || {
              echo "❌ Missing-epoch sync failed for $ENDPOINT with error:"
              cat "$error_file"
              exit 1
            })
            echo "$resp"
            isSynced=$(echo "$resp" | jq -r '.isSynced')
            syncedEpoch=$(echo "$resp" | jq -r '.syncedEpoch')
            totalMissing=$(echo "$resp" | jq -r '.totalMissing')

            if [[ "$isSynced" == "true" && "$syncedEpoch" == "null" ]]; then
              echo "✅ All epochs already synced"
              break
            elif [[ "$isSynced" == "true" ]]; then
              echo "✅ Synced epoch $syncedEpoch - All epochs synced"
              break
            fi

            next=$(echo "$resp" | jq -r '.next')
            echo "✅ Synced epoch $syncedEpoch, next epoch is $next ($totalMissing remaining)"
          done

      - name: Sync snapshot
        env:
          ENDPOINT: ${{ matrix.endpoint }}
        run: |
          echo "🔄 Syncing snapshot at $ENDPOINT"
          error_file=$(mktemp)
          curl -v -fsS "$ENDPOINT/api/v1/sync/snapshot" 2>"$error_file" || {
            echo "❌ Snapshot sync failed for $ENDPOINT with error:"
            cat "$error_file"
            exit 1
          }
          echo "✅ Snapshot sync completed successfully"
