name: Sync Matrix

on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  call-endpoints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint:
          # - https://validators-api-mainnet.pages.dev
          # - https://validators-api-testnet.pages.dev
          - https://dev.validators-api-mainnet.pages.dev
          - https://dev.validators-api-testnet.pages.dev
    steps:
      - name: Stream sync API
        run: |
          # --no-buffer (or -N) tells curl to flush each chunk as soon as it arrives,
          # so can see Nitro stream lines in real time.
          curl -fsS --no-buffer "${{ matrix.endpoint }}/api/v1/sync" | tee response.txt || {
            echo "Sync request failed for ${{ matrix.endpoint }}"
            exit 1
          }

          # Check for error messages in the stream response
          if grep -q '"kind":\s*"error"' response.txt; then
            echo "Error message detected in the stream response for ${{ matrix.endpoint }}"
            exit 1
          fi
